/**
 * This file was auto-generated by openapi-typescript-codegen.
 * Do not make direct changes to the file.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      weights: {
        Row: {
          id: string
          user_id: string
          date: string
          weight: number
          inserted_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date: string
          weight: number
          inserted_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          weight?: number
          inserted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "weights_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      workouts: {
        Row: {
          id: string
          user_id: string
          date: string
          name: string | null
          exercises: Json | null
          duration: number | null
          total_volume: number | null
          inserted_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date: string
          name?: string | null
          exercises?: Json | null
          duration?: number | null
          total_volume?: number | null
          inserted_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          name?: string | null
          exercises?: Json | null
          duration?: number | null
          total_volume?: number | null
          inserted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workouts_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      workout_exercises: {
        Row: {
          id: string
          workout_id: string
          name: string | null
          sets: Json | null
          inserted_at: string
        }
        Insert: {
          id?: string
          workout_id: string
          name?: string | null
          sets?: Json | null
          inserted_at?: string
        }
        Update: {
          id?: string
          workout_id?: string
          name?: string | null
          sets?: Json | null
          inserted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workout_exercises_workout_id_fkey"
            columns: ["workout_id"]
            referencedRelation: "workouts"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Helper types for common use cases
export type Weight = Database["public"]["Tables"]["weights"]["Row"]
export type WeightInsert = Database["public"]["Tables"]["weights"]["Insert"]
export type WeightUpdate = Database["public"]["Tables"]["weights"]["Update"]

export type Workout = Database["public"]["Tables"]["workouts"]["Row"]
export type WorkoutInsert = Database["public"]["Tables"]["workouts"]["Insert"]
export type WorkoutUpdate = Database["public"]["Tables"]["workouts"]["Update"]

export type WorkoutExercise = Database["public"]["Tables"]["workout_exercises"]["Row"]
export type WorkoutExerciseInsert = Database["public"]["Tables"]["workout_exercises"]["Insert"]
export type WorkoutExerciseUpdate = Database["public"]["Tables"]["workout_exercises"]["Update"]

// Exercise structure (stored in workouts.exercises JSONB)
export interface Exercise {
  key?: string
  display: string
  muscles?: string[]
  video?: string
  image?: string
  sets: ExerciseSet[]
  previousSets?: ExerciseSet[]
}

export interface ExerciseSet {
  weight: string | number
  reps: string | number
}

